"""empty message

Revision ID: 3f1dacd06fd6
Revises: 
Create Date: 2021-04-06 11:39:02.709106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1dacd06fd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pw', sa.String(length=64), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('usertype', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', 'nickname'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('post_history_table',
    sa.Column('_id2', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['usertable.id'], ),
    sa.PrimaryKeyConstraint('_id2'),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_history_table')
    op.drop_table('usertable')
    # ### end Alembic commands ###
